### ISSUE TITLE
Large screen support

### ISSUE THREAD

**Issue by at88mph** [wet-boew/theme-gcwu-fegc#162]
We're in the process of upgrading from 3.1.12 to 4.0.4.  I created an issue last year about supporting large screens (3000x1200), and was told that it was coming with the bootstrap functionality.

How is this implemented?  It's not working out of the box for this theme.  Do I need to extend it and implement the _screen-xl-min.scss file?

Thanks.

**Comment by LaurentGoderre** [comment]
Can we close this?

**Comment by at88mph** [comment]
Yes, thanks.
