### ISSUE TITLE
WET/GCWU: Tabbed Interface (jQuery-bound event handlers lost)

### ISSUE THREAD

**Issue by edward-smith** [wet-boew/theme-gcwu-fegc#198]
Implementing WET 4.0.9 (theme-gcwu-fegc) on an extra/public site. When using the tabbed interface plugin: 
```html
<div class="wb-tabs">
  <div class="tabpanels">
    <details id="basic"><button type="button" id="bound-element">Click me!</button></details>
  </div>
</div>
```

Any events I bind to elements in the tab panels are lost during the plugin's execution to 'tabify' the content. For example:
```javascript
$(document).ready(function() {
  $('button').on("click", function() { console.log('clicked'); });
});
```
will not be executed. As a work-around, I am using 
```javascript
$(document).ready(function() {
  setTimeout(function() {/* bind events here*/}, 500);
});
```
to delay my event binding, but this feels hack-y. Is there a wet-boew 'ready' event I can listen for to perform event binding after?

**Comment by LaurentGoderre** [comment]
@edward-smith It is easier to rely on event bubbling to manage event. This way, you don't need to wait for any event to bind your event. You can rewrite you code to the following which is shorter and simpler

```javascript
wb.doc.on("click", "'button'", function() { console.log('clicked'); });
```

Note the wb.doc is a cached version of the document element inside a jQuery object

**Comment by edward-smith** [comment]
Bubblerific! Thanks Laurent.

**Comment by LaurentGoderre** [comment]
I'm glad I could help!
