### ISSUE TITLE
Canada image should be higher / padding reduced

### ISSUE THREAD

**Issue by crochefort** [wet-boew/theme-gcwu-fegc#217]
As per this screenshot
![canada](https://cloud.githubusercontent.com/assets/4562025/8252998/449a7bd6-1659-11e5-98b4-e72258a8e550.jpg)

@LaurentGoderre @pjackson28

**Comment by crochefort** [comment]
Try it on this page : http://wet-boew.github.io/themes-dist/theme-gcwu-fegc/index-en.html
Chrome Version 43.0.2357.124 m
Firefox 35
and IE11

**Comment by pjackson28** [comment]
@crochefort Thank you for reporting this issue. Would you be able to create a fix for this?

**Comment by pjackson28** [comment]
I wonder of it is because the blue area around the search field is too thick. Could you please check and if it is the case could you change it to what it was before?

**Comment by pjackson28** [comment]
I know what is the problem. Something has set the min-height on the button (using .btn). Making this specific button return to a normal min-height fixes the issue.

**Comment by pjackson28** [comment]
Will be fixed by PR #218.

**Comment by upsonp** [comment]
Hi Christian,

Sorry I missed this issue. Were you able to figured out the issue?

If not you should check the zoom level that's been an issue for me a few
times in the past. I'll have to wait till I'm at work to check the page
with other browsers.

Doesn't seem to be an issue for me in FireFox 38 or Chromium 43.0.2357.81


On Fri, Jun 19, 2015 at 9:07 AM, crochefort <notifications@github.com>
wrote:

> Try it on this page :
> http://wet-boew.github.io/themes-dist/theme-gcwu-fegc/index-en.html
> Chrome Version 43.0.2357.124 m
> Firefox 35
> and IE11
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wet-boew/theme-gcwu-fegc/issues/217#issuecomment-113491687>
> .
>



-- 

Regards,
Patrick Upson

Twitter: @PatrickUpson

CIPS NS - Director at large

**Comment by LaurentGoderre** [comment]
It has been fixed
