### ISSUE TITLE
Government of Canada Web Usability theme:  Property attribute in some elements not parsing

### ISSUE THREAD

**Issue by juliemercier** [wet-boew/theme-gcwu-fegc#232]
In the WET4 template, the &#60;nav role="navigation" id="wb-bc" <strong>property</strong>="breadcrumb"&#62; and &#60;main role="main"<strong> property</strong>="mainContentOfPage" class="container"&#62; elements have a <strong>property</strong> "attribute". From what I can see at http://www.w3.org/TR/html51/semantics.html#the-main-element and http://www.w3.org/TR/html51/semantics.html#the-nav-element  the <strong>properties</strong> attribute is not an allowable attribute for these elements and our QA team is telling us that this is causing us to fail the WCAG 4.1.1 Parsing requirement. If the properties attribute is allowed, could you provide a link to supporting document please so I can show my QA team (and maybe learn something in the process)? Thank you.

**Comment by LaurentGoderre** [comment]
The attribute `property` is allowed as it is RDFa Lite. In any case, WCAG 4.1.1 is a failure only in a case of an syntax error which in this case isn't  syntax error.

WHen validating, you should be use http://validator.nu for validating HTML5 which is usually the most up to date. You will get warning about other attributes that we put there for backwards compatibility.

**Comment by juliemercier** [comment]
Thank you!
