### ISSUE TITLE
Bower package

### ISSUE THREAD

**Issue by vallieresc** [wet-boew/theme-gcwu-fegc#233]
This project should have a bower package!

Could you include a dist folder in the package that only includes the necessary minified files?

**Comment by LaurentGoderre** [comment]
All themes have a bower package. Here is an example on how to use them

https://github.com/open-data/report-generator/blob/master/bower.json#L18-L19

**Comment by vallieresc** [comment]
That's super! For some reason Visual Studio 2015 with .Net5 doesn't list your package but I see WET's.

What is the package for the web usability theme?
No fonts folder? I guess I use WET's fonts? Or Bootstrap's?

**Comment by MaximMartel** [comment]
@vallieresc 

Package for the Web usability theme can be found here : http://wet-boew.github.io/wet-boew/docs/versions/dwnld-en.html#v4020 
Government of Canada Web Usability - You can either download the source code or Production files.

**Comment by LaurentGoderre** [comment]
If you want the GC Web Usability Theme, use the following:

```
"wet-boew": "wet-boew/wet-boew-cdn#v4.0.20",
"theme-gcwu-fegc": "wet-boew/themes-cdn#v4.0.20-theme-gcwu-fegc",
```

**Comment by vallieresc** [comment]
@LaurentGoderre Thank you!

**Comment by LaurentGoderre** [comment]
Short of setting up an actual CDN, this is my preferred way to reference WET. You can also a `.bowerrc` with the following content to renamed the bower folder

```
{
  "directory": "lib"
}
```

This way you would reference wet by using `lib/wet-boew/...`
